arch:
- armhf
- armv7
- amd64
- aarch64
description: Yet another rss reader
image: ghcr.io/einschmidt/yarr/{arch}
map:
- share:rw
- ssl
name: yarr!
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  login:
    password: ''
    username: ''
  ssl: true
panel_icon: mdi:rss-box
ports:
  80/tcp: 7070
ports_description:
  80/tcp: Web interface
schema:
  certfile: str
  db_path: str?
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  login:
    password: password
    username: str
  ssl: bool
slug: yarr
url: https://github.com/einschmidt/addon-yarr
version: 0.2.2
