arch:
- i386
- armhf
- armv7
- amd64
- aarch64
description: A free, self-hostable feed aggregator
image: ghcr.io/einschmidt/freshrss/{arch}
init: false
map:
- ssl
name: freshrss
options:
  base_url: ''
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_icon: mdi:rss-box
ports:
  80/tcp: 7077
ports_description:
  80/tcp: Web interface
schema:
  base_url: str
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: freshrss
url: https://github.com/einschmidt/addon-freshrss
version: 0.1.0
